"""Pluggable storage backends for jhcontext server."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from ...models import Artifact, Decision, Envelope
from ...prov import PROVGraph


@runtime_checkable
class StorageBackend(Protocol):
    """Abstract storage backend for jhcontext server."""

    def save_envelope(self, envelope: Envelope) -> str: ...
    def get_envelope(self, context_id: str) -> Envelope | None: ...
    def list_envelopes(self, **filters: Any) -> list[Envelope]: ...

    def save_artifact(self, artifact_id: str, content: bytes, metadata: Artifact) -> str: ...
    def get_artifact(self, artifact_id: str) -> tuple[bytes, Artifact] | None: ...

    def save_prov_graph(self, context_id: str, graph_turtle: str, digest: str) -> str: ...
    def get_prov_graph(self, context_id: str) -> str | None: ...

    def save_decision(self, decision: Decision) -> str: ...
    def get_decision(self, decision_id: str) -> Decision | None: ...
